#ifndef QTWANGYONGLIN_GLOBAL_H
#define QTWANGYONGLIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTWANGYONGLIN_LIBRARY)
#  define QTWANGYONGLIN_EXPORT Q_DECL_EXPORT
#else
#  define QTWANGYONGLIN_EXPORT Q_DECL_IMPORT
#endif

#endif // QTWANGYONGLIN_GLOBAL_H
